# Generated by Django 5.2.3 on 2025-07-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('option_one', models.CharField(max_length=100)),
                ('option_two', models.CharField(max_length=100)),
                ('option_three', models.CharField(max_length=100)),
                ('votes_one', models.IntegerField(default=0)),
                ('votes_two', models.IntegerField(default=0)),
                ('votes_three', models.IntegerField(default=0)),
            ],
        ),
    ]
