# Generated by Django 5.2.3 on 2025-07-03 17:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='option_one',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='option_three',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='option_two',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='votes_one',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='votes_three',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='votes_two',
        ),
        migrations.AddField(
            model_name='poll',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('votes', models.IntegerField(default=0)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='quiz.poll')),
            ],
        ),
    ]
