# Generated by Django 5.2.4 on 2025-07-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quizresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='time_taken',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='difficulty',
            field=models.CharField(default='Medium', max_length=20),
        ),
    ]
