# Generated by Django 5.2.4 on 2025-07-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_quizresult_time_taken_alter_quizresult_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='difficulty',
            field=models.CharField(default='Medium', max_length=20),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='time_taken',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
