# Generated by Django 5.2.4 on 2025-07-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_quizattempt_difficulty_quizattempt_time_taken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='difficulty',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
