# Generated by Django 5.2.4 on 2025-07-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_leaderboardprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='questions',
            field=models.ManyToManyField(blank=True, to='quiz.quizquestion'),
        ),
    ]
