# Generated by Django 5.2.3 on 2025-07-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(default='cricket', max_length=100),
        ),
    ]
