# Generated by Django 5.2.4 on 2025-07-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='fav_ipl_team',
            field=models.CharField(blank=True, choices=[('CSK', 'Chennai Super Kings'), ('MI', 'Mumbai Indians'), ('RCB', 'Royal Challengers Bangalore'), ('KKR', 'Kolkata Knight Riders'), ('RR', 'Rajasthan Royals'), ('DC', 'Delhi Capitals'), ('LSG', 'Lucknow Super Giants'), ('GT', 'Gujarat Titans'), ('PBKS', 'Punjab Kings'), ('SRH', 'Sunrisers Hyderabad')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nickname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
