# Generated by Django 5.2.4 on 2025-07-16 17:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_fav_ipl_team_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('icon', models.ImageField(upload_to='achievements/')),
                ('users', models.ManyToManyField(related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
