# Generated by Django 5.2.4 on 2025-07-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_achievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='num_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
