# Generated by Django 5.2.4 on 2025-07-18 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_num_attempts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='num_attempts',
            new_name='quiz_attempts',
        ),
    ]
