# Generated by Django 5.2.4 on 2025-07-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_num_attempts_customuser_quiz_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='highest_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
