# Generated by Django 5.2.4 on 2025-07-19 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_highest_score'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Achievement',
        ),
    ]
