# Generated by Django 5.2.4 on 2025-08-02 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=7)),
                ('logo', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('Batsman', 'Batsman'), ('Bowler', 'Bowler'), ('All-rounder', 'All-rounder'), ('Wicket-keeper', 'Wicket-keeper')], max_length=20)),
                ('country', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('photo', models.URLField(blank=True, max_length=500)),
                ('batting_matches', models.IntegerField(default=0)),
                ('batting_runs', models.IntegerField(default=0)),
                ('batting_average', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('batting_strike_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('batting_fifties', models.IntegerField(default=0)),
                ('batting_hundreds', models.IntegerField(default=0)),
                ('batting_highest_score', models.IntegerField(default=0)),
                ('bowling_wickets', models.IntegerField(default=0)),
                ('bowling_average', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('bowling_economy', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('bowling_best_figures', models.CharField(default='0/0', max_length=10)),
                ('bowling_five_wickets', models.IntegerField(default=0)),
                ('fielding_catches', models.IntegerField(default=0)),
                ('fielding_stumpings', models.IntegerField(default=0)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='comparison.team')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
