# Generated by Django 5.2.4 on 2025-08-11 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comparison', '0002_delete_player_delete_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=20)),
                ('logo', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('role', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('photo', models.URLField(blank=True, null=True)),
                ('batting_matches', models.IntegerField(default=0)),
                ('batting_runs', models.IntegerField(default=0)),
                ('batting_average', models.FloatField(default=0)),
                ('batting_strike_rate', models.FloatField(default=0)),
                ('batting_fifties', models.IntegerField(default=0)),
                ('batting_hundreds', models.IntegerField(default=0)),
                ('batting_highest_score', models.IntegerField(default=0)),
                ('bowling_wickets', models.IntegerField(default=0)),
                ('bowling_average', models.FloatField(default=0)),
                ('bowling_economy', models.FloatField(default=0)),
                ('bowling_best_figures', models.CharField(blank=True, max_length=10)),
                ('bowling_five_wickets', models.IntegerField(default=0)),
                ('catches', models.IntegerField(default=0)),
                ('stumpings', models.IntegerField(default=0)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='comparison.team')),
            ],
        ),
    ]
