# Generated by Django 5.2.4 on 2025-08-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparison', '0004_alter_player_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='batting_average',
        ),
        migrations.RemoveField(
            model_name='player',
            name='batting_fifties',
        ),
        migrations.RemoveField(
            model_name='player',
            name='batting_highest_score',
        ),
        migrations.RemoveField(
            model_name='player',
            name='batting_hundreds',
        ),
        migrations.RemoveField(
            model_name='player',
            name='batting_matches',
        ),
        migrations.RemoveField(
            model_name='player',
            name='batting_runs',
        ),
        migrations.RemoveField(
            model_name='player',
            name='batting_strike_rate',
        ),
        migrations.RemoveField(
            model_name='player',
            name='bowling_average',
        ),
        migrations.RemoveField(
            model_name='player',
            name='bowling_best_figures',
        ),
        migrations.RemoveField(
            model_name='player',
            name='bowling_economy',
        ),
        migrations.RemoveField(
            model_name='player',
            name='bowling_five_wickets',
        ),
        migrations.RemoveField(
            model_name='player',
            name='bowling_wickets',
        ),
        migrations.RemoveField(
            model_name='player',
            name='catches',
        ),
        migrations.RemoveField(
            model_name='player',
            name='stumpings',
        ),
        migrations.AddField(
            model_name='player',
            name='stats',
            field=models.JSONField(default=dict),
        ),
    ]
