# Generated by Django 5.2 on 2025-07-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPLWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('team', models.CharField(max_length=100)),
                ('logo', models.URLField(max_length=500)),
                ('primaryColor', models.CharField(max_length=50)),
                ('secondaryColor', models.CharField(max_length=50)),
                ('videoPath', models.CharField(max_length=200)),
                ('captain', models.CharField(blank=True, max_length=100, null=True)),
                ('opponent', models.CharField(blank=True, max_length=100, null=True)),
                ('venue', models.CharField(blank=True, max_length=100, null=True)),
                ('margin', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
