# Generated by Django 5.2 on 2025-07-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iplwinner',
            name='primaryColor',
        ),
        migrations.RemoveField(
            model_name='iplwinner',
            name='secondaryColor',
        ),
        migrations.RemoveField(
            model_name='iplwinner',
            name='videoPath',
        ),
        migrations.AddField(
            model_name='iplwinner',
            name='primary_color',
            field=models.CharField(default='default_color', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iplwinner',
            name='secondary_color',
            field=models.CharField(default='default_color', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iplwinner',
            name='video_path',
            field=models.CharField(default='/static/react/videos/default.mp4', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='iplwinner',
            name='captain',
            field=models.CharField(blank=True, default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='iplwinner',
            name='logo',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='iplwinner',
            name='margin',
            field=models.CharField(blank=True, default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='iplwinner',
            name='opponent',
            field=models.CharField(blank=True, default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='iplwinner',
            name='venue',
            field=models.CharField(blank=True, default='Unknown', max_length=100),
            preserve_default=False,
        ),
    ]
