# Generated by Django 5.2 on 2025-07-30 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0002_remove_iplwinner_primarycolor_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IPLWinner',
        ),
    ]
