# Generated by Django 5.2.4 on 2025-07-19 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievement',
            old_name='title',
            new_name='name',
        ),
    ]
