"""
Django settings for cricarena project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ve4mrh*#cx5@ud+@+*y6(0!l!99i5q!0(127(@6vxk+*(4pkxf'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'cricarena-8.onrender.com','cricarena.onrender.com']
# Example for production:
# ALLOWED_HOSTS = ['localhost', '127.0.0.1', '::1']

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Apps
    'home',
    'news',
    'quiz',
    'stadium',
    'archives',
    'ipl',
    'sportscal',
    'crictactics',
    'comparison',
    'entrance',
    'accounts', 
    'blogpage',
    'rest_framework',
    'achievements',
    'aboutus',
    
    # Third-party
    'django_social_share',
    'django.contrib.sites',
    'django_crontab',
    'django_extensions',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cricarena.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cricarena.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'home' / 'static',
    BASE_DIR / 'news' / 'static',
    BASE_DIR / 'stadium' / 'static',
    BASE_DIR / 'archives' / 'static',
    BASE_DIR / 'ipl' / 'static',
    BASE_DIR / 'sportscal' / 'static',
    BASE_DIR / 'quiz' / 'static',
    BASE_DIR / 'crictactics' / 'static',
    BASE_DIR / 'comparison' / 'static',
    BASE_DIR / 'entrance' / 'static',
    BASE_DIR / 'accounts' / 'static',
    BASE_DIR / 'blogpage' / 'static',  
    BASE_DIR / 'achievements' / 'static',  
    BASE_DIR / 'aboutus' / 'static',  
]

AUTH_USER_MODEL = 'accounts.CustomUser'
LOGIN_REDIRECT_URL = '/home/'
LOGOUT_REDIRECT_URL = '/home/'

TEMPLATES[0]['DIRS'] += [BASE_DIR / 'stadium' / 'templates']
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Environment API keys
NEWSAPI_KEY = os.getenv('NEWSAPI_KEY')
CRICKETAPI_TOKEN = os.getenv('CRICKETAPI_TOKEN')

# Cron Jobs
CRONJOBS = [
    ('* * * * *', 'news.management.commands.fetch_articles.Command.handle'),  # every minute
]

# Site ID for django.contrib.sites (required by some packages like django-social-share)
SITE_ID = 1
